### ISSUE TITLE
ErrorException Required @OA\PathItem() not found

### ISSUE THREAD

**Issue by alexandre9865** [ManiruzzamanAkash/Laravel-Advanced-CRUD-API#4]
Using PHP 8.2, I cannot run `php artisan l5-swagger:generate`. 
The command returns  ErrorException Required @OA\PathItem() not found like that:

![Screenshot from 2023-05-31 13-25-55](https://github.com/ManiruzzamanAkash/Laravel-Advanced-CRUD-API/assets/11505122/0fcb417e-524d-4786-afcd-da079e9dd416)

I searched for a solution, but didn't find it.  I saw its ProductsController.php and saw the phpdoc comment block before the index method. What have I to do to solve that?

**Comment by mrjoebudi** [comment]
https://zircote.github.io/swagger-php/guide/faq.html#annotations-missing

> Using PHP 8.2, I cannot run `php artisan l5-swagger:generate`. The command returns ErrorException Required @OA\PathItem() not found like that:
> 
> ![Screenshot from 2023-05-31 13-25-55](https://user-images.githubusercontent.com/11505122/242343934-0fcb417e-524d-4786-afcd-da079e9dd416.png)
> 
> I searched for a solution, but didn't find it. I saw its ProductsController.php and saw the phpdoc comment block before the index method. What have I to do to solve that?
**try read documentation**
[https://zircote.github.io/swagger-php/guide/faq.html#annotations-missing](url)
